#!/usr/bin/env bash
# L4 render-twice idempotency guard for the W1-T4 Redis Sentinel HA tier
# (ADR-0044 §1 / P1-W4-LESSONS L4).
#
# THE TRAP (L4): a `helm upgrade` that REGENERATES the dev Redis password would no
# longer match the credential the running Redis primary/replicas + Sentinels were
# started with and would SEVER every broker / result-backend / replication /
# Sentinel-auth connection — exactly the CNPG superuser-password case. The Sentinel
# tier does NOT mint its own Secret: it consumes the SAME `redis-password` key the
# single-instance tier does, generated by the dev-fallback in templates/secret.yaml
# with the `lookup` REUSE-OR-GENERATE pattern (on upgrade the installed value is
# REUSED; only a first install / fresh CI render generates).
#
# This script is the LOCAL guard (no cluster needed — `helm template` only). It
# proves four things that together close the L4 trap for the Sentinel tier:
#   1. The reuse-or-generate branch for the redis key is WIRED in secret.yaml and
#      keyed on `lookup` of the prior Secret (a structural grep).
#   2. Two FRESH full-chart renders WITH the Sentinel tier enabled generate DISTINCT
#      redis passwords (no cluster => lookup empty => both generate), confirming
#      generation actually happens — so the reuse branch is the load-bearing
#      upgrade-stability guard, not decorative.
#   3. The REUSE branch is STABLE + verbatim: fed a FIXED prior, two renders yield a
#      BYTE-IDENTICAL password that EQUALS the injected prior (a `helm upgrade`
#      reusing the installed Secret never changes the password). `helm template`'s
#      real `lookup` cannot be primed without an API server, so this asserts the
#      reuse via the ci/redis-sentinel/reuse-fixture chart, which embeds the IDENTICAL
#      Sprig reuse idiom the production secret.yaml runs.
#   4. The Sentinel + Redis StatefulSets consume the redis password BY-REFERENCE
#      (valueFrom.secretKeyRef on REDIS_PASSWORD) and inline NO `value:` literal — the
#      credential never lands in the manifest/argv/ConfigMap (ADR-0029 §6 / ADR-0044 §1).
#
# The LIVE Sentinel failover on a REAL cluster (an actual primary loss → Sentinel
# promotes a replica, clients re-point via the sentinel:// URL) requires a cluster and
# is the W4-T1 kind drill — named-deferred (this host has no kind). Checks (3)+(4)
# assert the credential-stability + by-reference posture here and now.
#
# L5: `set -o pipefail` + `test -s` on every render so a masked helm exit / empty
# render reads as a failure, not a false-green.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../.." && pwd)"
CHART_DIR="${REPO_ROOT}/deploy/kubernetes/netops"
SECRET_TEMPLATE="${CHART_DIR}/templates/secret.yaml"
RS_TEMPLATE="${CHART_DIR}/templates/redis-sentinel.yaml"
FIXTURE_DIR="${HERE}/reuse-fixture"
# The dev-fallback secret extractor is shared with the CNPG guard (stdlib-only).
EXTRACT="${REPO_ROOT}/ci/cnpg/extract_stringdata.py"

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

fail=0
ok()  { echo "PASS: $*"; }
bad() { echo "FAIL: $*" >&2; fail=$((fail + 1)); }

PY="$(command -v python3 || command -v python)"
if [ -z "${PY}" ]; then
  echo "::error::no python3/python on PATH for the render-twice extractor" >&2
  exit 2
fi
extract() { "${PY}" "${EXTRACT}" "$1" "$2" "$3"; }

# --- 1. the reuse-or-generate branch for the redis key is wired -----------------
if grep -Eq 'lookup "v1" "Secret"' "${SECRET_TEMPLATE}"; then
  ok "dev-secrets template looks up the prior Secret (reuse-on-upgrade path present, L4)"
else
  bad "dev-secrets template must \`lookup\` the prior Secret to REUSE the redis password on upgrade (L4 regen-on-upgrade trap)"
fi
if grep -Eq 'redisKey' "${SECRET_TEMPLATE}" && grep -Eq 'hasKey \$priorData \$redisKey' "${SECRET_TEMPLATE}"; then
  ok "dev-secrets template REUSES the redis password (hasKey+index on the prior \$redisKey, L4)"
else
  bad "dev-secrets template must reuse the installed redis password on upgrade (hasKey+index on \$redisKey) (L4)"
fi

# --- 2. two FRESH renders generate DISTINCT redis passwords ---------------------
render_fresh() { # <out>
  set -o pipefail
  helm template netops "${CHART_DIR}" \
    --namespace netops --kube-version 1.29.0 \
    --set redisSentinel.enabled=true \
    --set services.redis.enabled=false \
    | tr -d '\r' > "$1"
  test -s "$1"
}
render_fresh "${WORK}/a.yaml"
render_fresh "${WORK}/b.yaml"

redis_a="$(extract "${WORK}/a.yaml" netops-dev-secrets redis-password)"
redis_b="$(extract "${WORK}/b.yaml" netops-dev-secrets redis-password)"

if [ -n "${redis_a}" ] && [ -n "${redis_b}" ]; then
  ok "both fresh Sentinel-tier renders produced a non-empty redis password"
else
  bad "a fresh Sentinel-tier render produced an EMPTY redis password (generation broken)"
fi
if [ "${redis_a}" != "${redis_b}" ]; then
  ok "two fresh renders generate DISTINCT redis passwords (so the lookup-reuse branch is the load-bearing upgrade-stability guard, L4)"
else
  bad "two fresh renders produced an IDENTICAL redis password — generation is a no-op; the L4 reuse guard cannot be load-bearing"
fi

# --- 3. the REUSE branch is STABLE + verbatim (the L4 upgrade-stability bite) ----
PRIOR_REDIS="redis-prior-pw-fixed-0001"
PRIOR_REDIS_B64="$(printf '%s' "${PRIOR_REDIS}" | base64 | tr -d '\n')"

render_reuse() { # <out>
  set -o pipefail
  helm template fx "${FIXTURE_DIR}" --namespace netops --kube-version 1.29.0 \
    --set prior.redisPasswordB64="${PRIOR_REDIS_B64}" \
    | tr -d '\r' > "$1"
  test -s "$1"
}
render_reuse "${WORK}/reuse_a.yaml"
render_reuse "${WORK}/reuse_b.yaml"

ra="$(extract "${WORK}/reuse_a.yaml" netops-dev-secrets redis-password)"
rb="$(extract "${WORK}/reuse_b.yaml" netops-dev-secrets redis-password)"

if [ "${ra}" = "${rb}" ]; then
  ok "reuse branch is STABLE across renders — render-twice idempotency holds (L4)"
else
  bad "reuse branch is UNSTABLE: the redis password differs across renders (an upgrade would re-issue it and sever auth, L4)"
fi
if [ "${ra}" = "${PRIOR_REDIS}" ]; then
  ok "reuse branch returns the prior redis password verbatim (no regen on upgrade, L4)"
else
  bad "reuse branch did NOT return the injected prior redis password — it regenerated (the L4 trap)"
fi

# --- 4. the Sentinel/Redis pods consume REDIS_PASSWORD BY-REFERENCE -------------
# Inspect the REDIS_PASSWORD env entry's OWN source (not a whole-file grep): a
# generic `name: REDIS_PASSWORD` + `secretKeyRef` anywhere check would PASS even if
# REDIS_PASSWORD flipped to an inline `value:` while some OTHER env var still used a
# Secret. Parse every manifest and require EACH REDIS_PASSWORD env to carry
# valueFrom.secretKeyRef and NO inline `value:` (ADR-0029 §6 / ADR-0044 §1).
if "${PY}" - "${WORK}/a.yaml" <<'PYEOF'
import sys, yaml
path = sys.argv[1]
seen = 0
with open(path, encoding="utf-8") as fh:
    docs = list(yaml.safe_load_all(fh))
for doc in docs:
    if not isinstance(doc, dict):
        continue
    spec = (((doc.get("spec") or {}).get("template") or {}).get("spec")) or {}
    for c in spec.get("containers", []) or []:
        for e in c.get("env", []) or []:
            if e.get("name") != "REDIS_PASSWORD":
                continue
            seen += 1
            vf = e.get("valueFrom") or {}
            if "value" in e or not (vf.get("secretKeyRef")):
                print(
                    f"REDIS_PASSWORD env in container {c.get('name')!r} is not a "
                    "bare valueFrom.secretKeyRef", file=sys.stderr,
                )
                sys.exit(1)
if seen == 0:
    print("no REDIS_PASSWORD env found in the Sentinel-tier render", file=sys.stderr)
    sys.exit(1)
sys.exit(0)
PYEOF
then
  ok "every REDIS_PASSWORD env sources its OWN valueFrom.secretKeyRef with no inline value (by-reference, ADR-0044 §1)"
else
  bad "a REDIS_PASSWORD env is not a bare valueFrom.secretKeyRef (an inline value: would defeat by-reference auth, ADR-0029 §6)"
fi
# The redis password literal must NOT leak into the rendered manifest as a value:
# (the by-reference env carries only the key NAME, never the secret value).
if grep -Eq 'value:[[:space:]]*"?'"${redis_a}" "${WORK}/a.yaml"; then
  bad "the generated redis password LEAKED as an inline value in the Sentinel-tier render — it must be by-reference only (ADR-0029 §6)"
else
  ok "the redis password never appears as an inline literal in the Sentinel-tier render (by-reference only)"
fi
# Structural: the redis-sentinel template never inlines a requirepass/auth-pass value.
if grep -Eq '(requirepass|masterauth|auth-pass)[[:space:]]+[A-Za-z0-9]{8,}' "${RS_TEMPLATE}"; then
  bad "redis-sentinel.yaml inlines a requirepass/masterauth/auth-pass literal — the password must come from \$REDIS_PASSWORD env, never the template (ADR-0029 §6)"
else
  ok "redis-sentinel.yaml never inlines a requirepass/masterauth/auth-pass literal (env-only, ADR-0029 §6)"
fi

echo "== Redis Sentinel render-twice summary: ${fail} failure(s) =="
if [ "${fail}" -ne 0 ]; then
  echo "::error::Redis Sentinel render-twice L4 guard found ${fail} violation(s)" >&2
  exit 1
fi
echo "Redis Sentinel render-twice L4 guard: all invariants hold."
