"""DR-runbook generator — deterministic Markdown for the four W5 drills (W5-T5).

ADR-0030 §5 / PRODUCTION.md §8 require the DR runbook to be GENERATED and kept
current, not hand-maintained — the Documentation Agent's dogfooding mandate. The
Documentation Agent ships two GENERATION modes (ADR-0019 §2/§3): a deterministic,
no-LLM renderer (network inventories, topology diagrams — "output matches the
source content exactly by construction") and an LLM-narrative renderer (per-device
runbooks). DR DRILL runbooks are operational procedures grounded in the chart's
authoritative drill facts (the rendered Job/CronJob + the per-tier `DRILL ...`
contract), NOT per-device narratives — so they are generated by the SAME
deterministic, no-LLM path the inventory tool uses. The facts below come straight
from the drill manifests + the per-tier harness contracts (one source of truth);
the renderer interpolates them into a stable template, so re-running it on a
config change regenerates a current runbook with zero drift and zero LLM calls.

OFFLINE-HONESTY (P1, this host): the Documentation Agent's LLM-narrative runbook
path (`app.agents.documentation.tools.generate_runbook`) needs a reachable
``BaseChatModel`` provider; none is available on the P1 build host (no Ollama / no
API key). Per the W5-T5 spec, we therefore commit (a) this deterministic
generation wiring and (b) the seeded runbooks it produces — and say so in the
runbook header + the G-REL evidence doc. We do NOT fabricate LLM-narrative output.
When a provider is wired in P2, the narrative-grounding sections can be layered on
top of these deterministic procedure tables (the facts stay the source of truth).

Run:  python -m full_platform.run_drill ...           # runs the drill
      python -m full_platform.runbook --out docs/runbooks   # (re)generates docs
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

#: Header stamped on every generated runbook so a reader knows it is generated.
_GENERATED_BANNER = (
    "> **GENERATED — do not edit by hand.** Produced by "
    "`full_platform.runbook` (W5-T5, deterministic / no-LLM, ADR-0019 §2 dogfooding "
    "mode). Re-run the generator after any drill config change to keep it current "
    "(freshness target <= 90 days once drills run in P2 — G-OBS).\n>\n"
    "> The Documentation Agent's LLM-narrative runbook path "
    "(`app.agents.documentation.tools.generate_runbook`) needs a reachable LLM "
    "provider, which the P1 build host does not have — so the narrative layer is "
    "deferred to P2 and these runbooks carry the deterministic procedure tables "
    "only (W5-T5 spec: no fabricated generated output)."
)


@dataclass(frozen=True)
class DrillRunbook:
    """The authoritative facts for one drill's runbook (one source of truth)."""

    slug: str
    title: str
    adr: str
    cadence: str
    objective: str
    backup_type: str
    job_name: str
    restore_source: str
    restore_target: str
    proves: list[str]
    drill_lines: list[str]
    steps: list[str]
    failure_modes: list[tuple[str, str]] = field(default_factory=list)

    def render(self) -> str:
        out: list[str] = [f"# {self.title}", "", _GENERATED_BANNER, ""]
        out += ["## Objective", "", self.objective, ""]
        out += [
            "## Facts",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| ADR | {self.adr} |",
            f"| Cadence (P2) | {self.cadence} |",
            f"| Backup-type label | `{self.backup_type}` |",
            f"| Job / CronJob | `{self.job_name}` |",
            f"| Restore source | {self.restore_source} |",
            f"| Restore target | {self.restore_target} |",
            "| Execution phase | P2 (built P1, suspended CronJob) |",
            "",
        ]
        out += ["## What this drill proves", ""]
        out += [f"- {p}" for p in self.proves]
        out += [""]
        out += ["## Procedure", ""]
        out += [f"{i}. {s}" for i, s in enumerate(self.steps, start=1)]
        out += [""]
        out += [
            "## Structured evidence (the `DRILL ...` lines the collector parses)",
            "",
            "```",
            *self.drill_lines,
            "```",
            "",
        ]
        if self.failure_modes:
            out += ["## Failure modes & response", "", "| Symptom | Response |", "|---|---|"]
            out += [f"| {sym} | {resp} |" for sym, resp in self.failure_modes]
            out += [""]
        out += [
            "## Roll-back / safety",
            "",
            "- The drill writes ONLY to a throwaway `emptyDir` scratch torn down with "
            "the pod; it mounts no live PVC, so there is nothing to roll back and no "
            "production data is touched (ADR-0030 §5.3).",
            "- To stop a P2 run mid-flight: `kubectl delete job "
            f"{self.job_name}` (the CronJob stays suspended until deliberately "
            "un-suspended).",
            "",
        ]
        return "\n".join(out)


# --- The four drill runbooks. Facts mirror the rendered manifests + per-tier
# harness contracts (W5-T2/T3/T4 + the W5-T5 composing drill) — one source of
# truth; the generator never invents a value the chart does not declare. ---

_PITR = DrillRunbook(
    slug="postgres-pitr",
    title="DR Runbook — Postgres PITR restore drill (W5-T2)",
    adr="ADR-0030 §5/§5.1, ADR-0011 §1/§2",
    cadence="Quarterly (02:00, 1st of Jan/Apr/Jul/Oct)",
    objective=(
        "Prove the encrypted pgBackRest backup tier (W5-T1) is restorable: restore "
        "the latest full + WAL from the object-store repo ALONE into a throwaway "
        "target and assert the four properties a naive `pg_restore` would skip."
    ),
    backup_type="drill",
    job_name="netops-postgres-pitr-drill",
    restore_source="pgBackRest object-store repo (MinIO/S3) ALONE",
    restore_target="throwaway emptyDir scratch via `--pg1-path` (never the live PVC)",
    proves=[
        "RPO-in-window — WAL replay reached within the PROPOSED window (<= 5 min).",
        "Audit-log immutability — the restored append-only audit log is still "
        "UPDATE/DELETE-locked and not truncated.",
        "Credentials fail CLOSED — a restored credential decrypts ONLY with the "
        "matching KEK and raises a typed error (no plaintext) without it.",
        "pgbackrest verify — the restored stanza verifies clean.",
    ],
    drill_lines=[
        "DRILL postgres_pitr rpo_within_window=PASS duration_s=<n>",
        "DRILL postgres_pitr audit_log_immutable=PASS duration_s=<n>",
        "DRILL postgres_pitr credentials_fail_closed=PASS duration_s=<n>",
        "DRILL postgres_pitr pgbackrest_verify_clean=PASS duration_s=<n>",
        "DRILL postgres_pitr OUTCOME=PASS assertions=4",
    ],
    steps=[
        "Confirm the backup repo is reachable and the cipher pass / S3 credential "
        "are present in the platform Secret (by-reference only).",
        "Run the on-demand Job: `kubectl create job --from=cronjob/"
        "netops-postgres-pitr-drill netops-postgres-pitr-drill-manual`.",
        "The pod restores into the throwaway scratch, runs `pgbackrest verify`, then "
        "`python -m postgres_pitr.run_drill` (the four assertions).",
        "Collect the `DRILL postgres_pitr ...` lines for the G-REL evidence doc.",
    ],
    failure_modes=[
        ("`rpo_within_window=FAIL`", "WAL replay lag exceeded the PROPOSED window — "
         "investigate archive_command / WAL shipping cadence (W5-T1)."),
        ("`credentials_fail_closed=FAIL`", "A restored credential decrypted WITHOUT "
         "the KEK — envelope encryption is broken; escalate (G-SEC)."),
        ("Empty restore / `PG_VERSION` missing", "The L5 `test -s` guard failed the "
         "job — the restore stream was silently empty; check repo + stanza."),
    ],
)

_NEO4J = DrillRunbook(
    slug="neo4j-rebuild",
    title="DR Runbook — Neo4j rebuild drill (W5-T3)",
    adr="ADR-0030 §2/§5.2, ADR-0005 D5",
    cadence="Quarterly (02:00, 15th of Jan/Apr/Jul/Oct)",
    objective=(
        "Prove Neo4j needs NO backup: DR is a full RE-PROJECTION from the "
        "authoritative Postgres, not a restore of a graph dump. Drop/recreate the "
        "projected graph, re-project the WHOLE inventory, and assert the rebuilt "
        "counts match within the topology-RTO budget."
    ),
    backup_type="neo4j-rebuild-drill",
    job_name="netops-neo4j-rebuild-drill",
    restore_source="the authoritative Postgres (re-projected, NOT a graph dump)",
    restore_target="a clean Neo4j graph (re-derived; no PVC restore)",
    proves=[
        "Counts-match — rebuilt node/edge counts equal the pre-wipe projection "
        "within tolerance (the rebuildable-projection invariant, ADR-0005 D5).",
        "Topology-RTO — `topology_rebuild_seconds` < the PROPOSED budget "
        "(< 30 min at 5,000 devices).",
    ],
    drill_lines=[
        "DRILL neo4j_rebuild rto_within_target=PASS",
        "DRILL neo4j_rebuild counts_match=PASS",
        "DRILL neo4j_rebuild seconds=<n> nodes=<n> edges=<n> result=PASS",
        "DRILL neo4j_rebuild OUTCOME=PASS assertions=2",
    ],
    steps=[
        "Confirm Postgres is the authoritative inventory source and Neo4j auth is "
        "present in the platform Secret (by-reference).",
        "Run the on-demand Job from `cronjob/netops-neo4j-rebuild-drill`.",
        "The pod re-projects via `app.engines.topology` (recording "
        "`topology_rebuild_seconds` + node/edge gauges) and runs "
        "`python -m topology_rebuild.run_drill`.",
        "Collect the `DRILL neo4j_rebuild ...` lines (incl. the measured "
        "topology-RTO seconds) for the G-REL evidence doc.",
    ],
    failure_modes=[
        ("`counts_match=FAIL`", "The re-projection dropped or invented topology — "
         "the projection pipeline is incomplete (ADR-0005 D5); fix the projector."),
        ("`rto_within_target=FAIL`", "Rebuild exceeded the PROPOSED topology-RTO — "
         "profile the projection at scale; re-base the target on Consultant §12."),
    ],
)

_PCAP = DrillRunbook(
    slug="pcap-spot-restore",
    title="DR Runbook — pcap spot-restore drill (W5-T4)",
    adr="ADR-0030 §3/§5.4, ADR-0023 §3/§4/§5",
    cadence="Annual (03:00, Jan 2nd)",
    objective=(
        "Prove DR HONORS the pcap retention contract: a sampled live capture "
        "restores and sha256-matches its capture-time hash, a tombstoned capture is "
        "NEVER resurrected, and the restore stays engineer+ gated."
    ),
    backup_type="pcap-drill",
    job_name="netops-pcap-spot-restore-drill",
    restore_source="the `pcaps/` object-store prefix ALONE",
    restore_target="throwaway emptyDir scratch (never the live capture volume)",
    proves=[
        "Live-restore + sha256 — a sampled live capture's restored bytes match the "
        "capture-time hash (ADR-0023 §3 integrity).",
        "No resurrection — a tombstoned/expired capture is absent from the restore "
        "set, and a forced one is dropped by the metadata guard (ADR-0030 §3).",
        "Gated access — the restore is refused for a sub-engineer actor "
        "(ADR-0023 §5); DR opens no new ungated read path to PII/credential payloads.",
    ],
    drill_lines=[
        "DRILL pcap_spot_restore restore_authorized=PASS",
        "DRILL pcap_spot_restore sampled_sha256_matches=PASS",
        "DRILL pcap_spot_restore no_tombstoned_resurrection=PASS",
        "DRILL pcap_spot_restore sampled=<id> sha256=MATCH tombstoned_resurrected=NO result=PASS",
        "DRILL pcap_spot_restore OUTCOME=PASS assertions=3",
    ],
    steps=[
        "Confirm the engineer+ actor identity and that the pcap S3 credential + DB "
        "password are present in the platform Secret (by-reference).",
        "Run the on-demand Job from `cronjob/netops-pcap-spot-restore-drill`.",
        "The pod restores sampled captures into the throwaway scratch and runs "
        "`python -m pcap.run_drill` (the three assertions, incl. the negative "
        "no-resurrection self-check).",
        "Collect the `DRILL pcap_spot_restore ...` lines for the G-REL evidence doc.",
    ],
    failure_modes=[
        ("`no_tombstoned_resurrection=FAIL`", "A purged capture came back — DR "
         "re-extended a payload past retention; STOP and escalate (ADR-0030 §3)."),
        ("`sampled_sha256_matches=FAIL`", "Restore lost/corrupted bytes — investigate "
         "object-store integrity / the snapshot pipeline (W5-T4)."),
        ("`restore_authorized=FAIL`", "Expected for a sub-engineer actor — the gate "
         "bit; re-run as engineer+ for the positive path."),
    ],
)

_FULL = DrillRunbook(
    slug="full-platform",
    title="DR Runbook — full-platform DR drill (W5-T5)",
    adr="ADR-0030 §5.3/§6, ADR-0005 D5, ADR-0011 §1/§2",
    cadence="Semiannual / >= twice yearly (04:00, 20th of Jan + Jul)",
    objective=(
        "Prove the WHOLE platform is recoverable from object storage ALONE onto a "
        "clean cluster, by chaining the three per-tier drills end-to-end and "
        "asserting RPO <= 5 min / RTO <= 1 h (PROPOSED) at the measured scale."
    ),
    backup_type="full-platform-drill",
    job_name="netops-full-platform-dr-drill",
    restore_source="object storage ALONE (no surviving live state)",
    restore_target="a clean target — throwaway emptyDir scratch (no live PVC)",
    proves=[
        "From backups alone, onto a clean cluster — Postgres from object storage, "
        "Neo4j rebuilt over the RESTORED Postgres, pcaps spot-restored (G-REL).",
        "The D5 'one authoritative thing to restore (Postgres) + one thing to "
        "rebuild (the Neo4j projection)' story, end-to-end.",
        "Aggregated RPO/RTO/topology-RTO recorded vs the PROPOSED targets (the "
        "evidence collector parses the per-tier `DRILL ...` lines; it does NOT "
        "re-implement the per-tier assertions).",
    ],
    drill_lines=[
        "# (the three per-tier OUTCOME lines, then the composite:)",
        "DRILL postgres_pitr OUTCOME=PASS assertions=4",
        "DRILL neo4j_rebuild OUTCOME=PASS assertions=2",
        "DRILL pcap_spot_restore OUTCOME=PASS assertions=3",
        "DRILL full_platform tiers=3 passed=3 rpo_s=<n> rto_s=<n> "
        "topology_rto_s=<n> result=PASS",
    ],
    steps=[
        "Confirm all per-tier credentials are present in the platform Secret "
        "(by-reference only): DB password, Neo4j auth, backup + pcap S3 keys, repo "
        "cipher pass, KEK reference.",
        "Run the on-demand Job from `cronjob/netops-full-platform-dr-drill`.",
        "The pod restores Postgres from the repo ALONE into throwaway scratch, then "
        "runs `python -m full_platform.run_drill`, which chains tier 1 -> 2 -> 3 and "
        "aggregates their `DRILL ...` lines.",
        "Record the composite `DRILL full_platform ...` line + the aggregated table "
        "in `docs/roadmap/evidence/P1-W5-G-REL-evidence.md` (measured-vs-PROPOSED).",
        "P2 only: re-run at certified scale (5,000 devices) on a genuinely clean "
        "cluster and re-base the PROPOSED targets on the Consultant §12 answer.",
    ],
    failure_modes=[
        ("Any per-tier `OUTCOME=FAIL`", "The end-to-end result rolls up to FAIL; the "
         "aggregated table names which tier + assertion failed — follow that tier's "
         "runbook."),
        ("`full_platform ... result=FAIL` with a MISSING tier", "A tier produced no "
         "terminal verdict (silent gap) — the chain ran all tiers, so check that "
         "tier's pod logs; a missing tier is never a pass."),
        ("`rto_s` over budget", "End-to-end RTO exceeded the PROPOSED 1 h — record "
         "the measured number; re-base on Consultant §12 (do not weaken the gate)."),
    ],
)

ALL_RUNBOOKS: list[DrillRunbook] = [_PITR, _NEO4J, _PCAP, _FULL]


def generate(out_dir: Path) -> list[Path]:
    """Render all four runbooks into ``out_dir`` as ``dr-<slug>.md``; return paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for rb in ALL_RUNBOOKS:
        path = out_dir / f"dr-{rb.slug}.md"
        path.write_text(rb.render() + "\n", encoding="utf-8")
        written.append(path)
    return written


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="full_platform.runbook")
    parser.add_argument(
        "--out",
        default="docs/runbooks",
        help="output directory for the generated dr-*.md runbooks.",
    )
    return parser.parse_args(list(argv) if argv is not None else None)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    written = generate(Path(args.out))
    for p in written:
        print(f"generated {p}")
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised via the generator wrapper
    sys.exit(main())
