"""UuidPkMixin / TimestampMixin behavior on a real (sqlite) session."""

from __future__ import annotations

import asyncio
import uuid
from datetime import UTC, datetime, timedelta, timezone

import pytest
from sqlalchemy import select
from sqlalchemy.exc import StatementError
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Device


async def test_uuid_pk_generated_app_side(session: AsyncSession) -> None:
    """Primary keys are uuid4 values generated by the app, not the database."""
    first = Device(hostname="sw-1", mgmt_ip="192.0.2.1")
    second = Device(hostname="sw-2", mgmt_ip="192.0.2.2")
    session.add_all([first, second])
    await session.flush()

    assert isinstance(first.id, uuid.UUID)
    assert isinstance(second.id, uuid.UUID)
    assert first.id != second.id
    assert first.id.version == 4


async def test_timestamps_are_aware_utc(session: AsyncSession, device: Device) -> None:
    """created_at/updated_at default to tz-aware UTC and survive a reload."""
    await session.commit()

    reloaded = (
        await session.execute(
            select(Device).where(Device.id == device.id).execution_options(populate_existing=True)
        )
    ).scalar_one()

    for value in (reloaded.created_at, reloaded.updated_at):
        assert value.tzinfo == UTC
    assert reloaded.updated_at >= reloaded.created_at


async def test_updated_at_refreshes_on_update(session: AsyncSession, device: Device) -> None:
    """An UPDATE advances updated_at while created_at stays fixed."""
    created_before = device.created_at
    updated_before = device.updated_at

    await asyncio.sleep(0.01)
    device.hostname = "lab-sw-01-renamed"
    await session.flush()
    await session.refresh(device)

    assert device.created_at == created_before
    assert device.updated_at > updated_before


async def test_naive_datetime_rejected(session: AsyncSession, device: Device) -> None:
    """UtcDateTime columns refuse naive datetimes at bind time."""
    device.last_discovered_at = datetime(2026, 6, 10, 12, 0, 0)  # noqa: DTZ001 - intentionally naive
    with pytest.raises(StatementError):
        await session.flush()
    await session.rollback()


async def test_non_utc_aware_datetime_normalized_to_utc(
    session: AsyncSession, device: Device
) -> None:
    """Aware non-UTC datetimes are stored and returned as the same UTC instant."""
    offset = timezone(timedelta(hours=5))
    local_instant = datetime(2026, 6, 10, 17, 30, 0, tzinfo=offset)

    device.last_discovered_at = local_instant
    await session.commit()

    reloaded = (
        await session.execute(
            select(Device).where(Device.id == device.id).execution_options(populate_existing=True)
        )
    ).scalar_one()
    assert reloaded.last_discovered_at is not None
    assert reloaded.last_discovered_at.tzinfo == UTC
    assert reloaded.last_discovered_at == local_instant
