"""M1 baseline: identity, inventory, evidence, audit — plus RBAC/admin seeds.

Hand-written (not autogenerated) so the PostgreSQL-only DDL can be expressed.
On the postgresql dialect, ``audit_log`` and ``raw_artifacts`` are created
``PARTITION BY RANGE (created_at)`` with monthly partitions for 2026-06 and
2026-07 plus a DEFAULT partition, and ``audit_log`` is locked append-only via
``REVOKE UPDATE, DELETE`` (ADR-0011). On other dialects (the SQLite unit-test
backend) the same tables are created unpartitioned — the partition option is
a no-op there.

Seeds: the four RBAC roles (viewer < operator < engineer < admin, ADR-0010)
and an ``admin`` user whose bcrypt hash comes from ``NETOPS_ADMIN_PASSWORD``
(defaulting to "admin" with a loud migration warning when unset).

Revision ID: 0001
Revises:
Create Date: 2026-06-11
"""

from __future__ import annotations

import logging
import os
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.security import hash_password

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

logger = logging.getLogger("alembic.runtime.migration")

#: Portable JSON column: plain JSON everywhere, JSONB on PostgreSQL. Mirrors
#: app.models.mixins.JSON_VARIANT (migrations never import models — D4).
_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

#: Tables range-partitioned by ``created_at`` on PostgreSQL (ADR-0011, D11).
_PARTITIONED_TABLES: tuple[str, ...] = ("audit_log", "raw_artifacts")

#: Monthly partition windows (suffix, lower bound, upper bound) — explicit
#: ``+00`` offsets so the bounds do not shift with the session timezone.
_PARTITION_WINDOWS: tuple[tuple[str, str, str], ...] = (
    ("2026_06", "2026-06-01 00:00:00+00", "2026-07-01 00:00:00+00"),
    ("2026_07", "2026-07-01 00:00:00+00", "2026-08-01 00:00:00+00"),
)

#: Fixed RBAC role set (ADR-0010); rank comparison lives in the auth layer.
_ROLE_NAMES: tuple[str, ...] = ("viewer", "operator", "engineer", "admin")

#: Deterministic seed ids: stable across runs, reviewable in --sql output.
_SEED_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_DNS, "seed.netops.platform")


def _seed_id(kind: str, name: str) -> uuid.UUID:
    return uuid.uuid5(_SEED_NAMESPACE, f"{kind}:{name}")


def _is_postgresql() -> bool:
    """Dialect guard safe in both online and offline (``--sql``) mode."""
    return op.get_context().dialect.name == "postgresql"


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------


def upgrade() -> None:
    _create_identity_tables()
    _create_inventory_tables()
    _create_evidence_and_audit_tables()
    _create_normalized_tables()
    _seed_roles_and_admin()


def _create_identity_tables() -> None:
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_users_role_id")),
    )
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"])


def _create_inventory_tables() -> None:
    op.create_table(
        "device_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
        sa.Column("dek_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("kek_version", sa.String(length=64), nullable=False),
        sa.Column("params", _JSON, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_credentials")),
        sa.UniqueConstraint("name", name=op.f("uq_device_credentials_name")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("mgmt_ip", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("os_version", sa.String(length=128), nullable=True),
        sa.Column("serial", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("mgmt_ip", name=op.f("uq_devices_mgmt_ip")),
        sa.ForeignKeyConstraint(
            ["credential_id"], ["device_credentials.id"], name=op.f("fk_devices_credential_id")
        ),
    )
    op.create_index(op.f("ix_devices_hostname"), "devices", ["hostname"])
    op.create_index(op.f("ix_devices_credential_id"), "devices", ["credential_id"])
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("seeds", _JSON, nullable=False),
        sa.Column("hop_limit", sa.Integer(), nullable=False),
        sa.Column("allowlist", _JSON, nullable=False),
        sa.Column("credential_names", _JSON, nullable=False),
        sa.Column("stats", _JSON, nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_runs")),
    )


def _create_evidence_and_audit_tables() -> None:
    # Range partitioning requires the partition key in the PK, hence the
    # composite (id, created_at) primary keys (see app/models/audit.py).
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=128), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("detail", _JSON, nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("pk_audit_log")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_table(
        "raw_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("command", sa.String(length=255), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("parsed", _JSON, nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("pk_raw_artifacts")),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_raw_artifacts_device_id")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["discovery_runs.id"], name=op.f("fk_raw_artifacts_run_id")
        ),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(op.f("ix_raw_artifacts_device_id"), "raw_artifacts", ["device_id"])
    op.create_index(op.f("ix_raw_artifacts_run_id"), "raw_artifacts", ["run_id"])

    if not _is_postgresql():
        return

    for parent in _PARTITIONED_TABLES:
        for suffix, lower, upper in _PARTITION_WINDOWS:
            op.execute(
                f"CREATE TABLE {parent}_{suffix} PARTITION OF {parent} "
                f"FOR VALUES FROM ('{lower}') TO ('{upper}')"
            )
        op.execute(f"CREATE TABLE {parent}_default PARTITION OF {parent} DEFAULT")

    # Append-only audit log (ADR-0011): block UPDATE/DELETE by default.
    # Caveat: REVOKE ... FROM PUBLIC cannot bind the table OWNER (or
    # superusers) — PostgreSQL owners always hold implicit privileges. Real
    # enforcement requires the application to connect as a NON-OWNER role
    # that is granted only INSERT/SELECT on audit_log (deployment concern);
    # this statement keeps any incidental PUBLIC access closed by default.
    # Partitions reached directly (not via the parent) carry their own ACLs.
    op.execute("REVOKE UPDATE, DELETE ON audit_log FROM PUBLIC")


def _create_normalized_tables() -> None:
    # Provenance columns are shared via app/models/inventory.py::_ProvenanceMixin.
    # raw_artifact_id is a plain indexed UUID — no FK to the partitioned
    # raw_artifacts table (PostgreSQL would require the partition key in the
    # FK); linkage integrity is enforced by tests (M1-18).
    op.create_table(
        "normalized_interfaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("raw_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_vendor", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("admin_status", sa.String(length=32), nullable=False),
        sa.Column("oper_status", sa.String(length=32), nullable=False),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("mtu", sa.Integer(), nullable=True),
        sa.Column("speed_mbps", sa.Integer(), nullable=True),
        sa.Column("duplex", sa.String(length=32), nullable=True),
        sa.Column("vlan_id", sa.Integer(), nullable=True),
        sa.Column("input_errors", sa.BigInteger(), nullable=True),
        sa.Column("output_errors", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_interfaces")),
        sa.UniqueConstraint("device_id", "name", name=op.f("uq_normalized_interfaces_device_id")),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_normalized_interfaces_device_id")
        ),
    )
    op.create_index(
        op.f("ix_normalized_interfaces_device_id"), "normalized_interfaces", ["device_id"]
    )
    op.create_index(
        op.f("ix_normalized_interfaces_raw_artifact_id"),
        "normalized_interfaces",
        ["raw_artifact_id"],
    )
    op.create_table(
        "normalized_routes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("raw_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_vendor", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=64), nullable=False),
        sa.Column("protocol", sa.String(length=32), nullable=False),
        sa.Column("next_hop", sa.String(length=64), nullable=False),
        sa.Column("interface", sa.String(length=255), nullable=False),
        sa.Column("vrf", sa.String(length=64), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.Column("metric", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_routes")),
        sa.UniqueConstraint(
            "device_id",
            "vrf",
            "prefix",
            "protocol",
            "next_hop",
            "interface",
            name=op.f("uq_normalized_routes_device_id"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_normalized_routes_device_id")
        ),
    )
    op.create_index(op.f("ix_normalized_routes_device_id"), "normalized_routes", ["device_id"])
    op.create_index(
        op.f("ix_normalized_routes_raw_artifact_id"), "normalized_routes", ["raw_artifact_id"]
    )
    op.create_table(
        "normalized_neighbors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("raw_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_vendor", sa.String(length=64), nullable=False),
        sa.Column("protocol", sa.String(length=32), nullable=False),
        sa.Column("local_interface", sa.String(length=255), nullable=False),
        sa.Column("neighbor_name", sa.String(length=255), nullable=False),
        sa.Column("neighbor_interface", sa.String(length=255), nullable=False),
        sa.Column("neighbor_platform", sa.String(length=255), nullable=True),
        sa.Column("neighbor_address", sa.String(length=64), nullable=True),
        sa.Column("neighbor_capabilities", _JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_neighbors")),
        sa.UniqueConstraint(
            "device_id",
            "protocol",
            "local_interface",
            "neighbor_name",
            "neighbor_interface",
            name=op.f("uq_normalized_neighbors_device_id"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_normalized_neighbors_device_id")
        ),
    )
    op.create_index(
        op.f("ix_normalized_neighbors_device_id"), "normalized_neighbors", ["device_id"]
    )
    op.create_index(
        op.f("ix_normalized_neighbors_raw_artifact_id"),
        "normalized_neighbors",
        ["raw_artifact_id"],
    )


def _seed_roles_and_admin() -> None:
    timestamp = sa.func.current_timestamp()

    roles = sa.table(
        "roles",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.execute(
        roles.insert().values(
            [
                {
                    "id": _seed_id("role", name),
                    "name": name,
                    "created_at": timestamp,
                    "updated_at": timestamp,
                }
                for name in _ROLE_NAMES
            ]
        )
    )

    password = os.environ.get("NETOPS_ADMIN_PASSWORD") or ""
    if not password:
        password = "admin"
        logger.warning(
            "NETOPS_ADMIN_PASSWORD is not set; seeding the 'admin' user with the insecure "
            "default password — set NETOPS_ADMIN_PASSWORD and rotate this account immediately"
        )

    users = sa.table(
        "users",
        sa.column("id", sa.Uuid()),
        sa.column("username", sa.String()),
        sa.column("password_hash", sa.String()),
        sa.column("role_id", sa.Uuid()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.execute(
        users.insert().values(
            id=_seed_id("user", "admin"),
            username="admin",
            password_hash=hash_password(password),
            role_id=_seed_id("role", "admin"),
            is_active=True,
            created_at=timestamp,
            updated_at=timestamp,
        )
    )


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------


def downgrade() -> None:
    op.drop_table("normalized_neighbors")
    op.drop_table("normalized_routes")
    op.drop_table("normalized_interfaces")

    if _is_postgresql():
        # Explicitly drop partitions in reverse creation order before the
        # parents (DROP TABLE on the parent would cascade, but the reverse
        # of upgrade() is kept literal and reviewable).
        for parent in reversed(_PARTITIONED_TABLES):
            op.execute(f"DROP TABLE {parent}_default")
            for suffix, _lower, _upper in reversed(_PARTITION_WINDOWS):
                op.execute(f"DROP TABLE {parent}_{suffix}")
        # The upgrade-time REVOKE needs no inverse: PUBLIC holds no table
        # privileges by default, and the table is dropped below anyway.

    op.drop_table("raw_artifacts")
    op.drop_table("audit_log")
    op.drop_table("discovery_runs")
    op.drop_table("devices")
    op.drop_table("device_credentials")
    op.drop_table("users")
    op.drop_table("roles")
