"""M3-01: agent_sessions + reasoning_traces persistence.

Hand-written (not autogenerated) so the PostgreSQL-only partitioning DDL can be
expressed. On the postgresql dialect, ``reasoning_traces`` and
``reasoning_trace_steps`` are created ``PARTITION BY RANGE (created_at)`` with
monthly partitions for 2026-06 and 2026-07 plus a DEFAULT partition — the exact
mechanism the 0001 baseline uses for ``audit_log`` / ``raw_artifacts``. On other
dialects (the SQLite unit-test backend) the same tables are created
unpartitioned (the partition option is a no-op there).

Links: ``audit_log`` gains a nullable ``reasoning_trace_id`` column pointing at
the trace that produced an audited action (brief §6). Like ``raw_artifact_id``
it is a plain indexed UUID with no FK — PostgreSQL FKs to a partitioned table
must include the partition key.

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-13
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Portable JSON column: plain JSON everywhere, JSONB on PostgreSQL. Mirrors
#: app.models.mixins.JSON_VARIANT (migrations never import models — D4).
_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

#: Trace tables range-partitioned by ``created_at`` on PostgreSQL (ADR-0011),
#: same precedent as audit_log / raw_artifacts in the 0001 baseline.
_PARTITIONED_TABLES: tuple[str, ...] = ("reasoning_traces", "reasoning_trace_steps")

#: Monthly partition windows (suffix, lower bound, upper bound) — explicit
#: ``+00`` offsets so the bounds do not shift with the session timezone.
#: Identical windows to the 0001 baseline.
_PARTITION_WINDOWS: tuple[tuple[str, str, str], ...] = (
    ("2026_06", "2026-06-01 00:00:00+00", "2026-07-01 00:00:00+00"),
    ("2026_07", "2026-07-01 00:00:00+00", "2026-08-01 00:00:00+00"),
)


def _is_postgresql() -> bool:
    """Dialect guard safe in both online and offline (``--sql``) mode."""
    return op.get_context().dialect.name == "postgresql"


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------


def upgrade() -> None:
    _create_agent_sessions()
    _create_reasoning_traces()
    _create_reasoning_trace_steps()
    _create_partitions()
    _link_audit_log_to_traces()


def _create_agent_sessions() -> None:
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("invoking_role", sa.String(length=64), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_sessions")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_agent_sessions_user_id")),
    )
    op.create_index(op.f("ix_agent_sessions_user_id"), "agent_sessions", ["user_id"])


def _create_reasoning_traces() -> None:
    # Range partitioning requires the partition key in the PK, hence the
    # composite (id, created_at) primary key (see app/models/agents.py).
    op.create_table(
        "reasoning_traces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("agent_name", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("pk_reasoning_traces")),
        sa.ForeignKeyConstraint(
            ["session_id"], ["agent_sessions.id"], name=op.f("fk_reasoning_traces_session_id")
        ),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(op.f("ix_reasoning_traces_session_id"), "reasoning_traces", ["session_id"])


def _create_reasoning_trace_steps() -> None:
    # trace_id is a plain indexed UUID — no FK to the partitioned
    # reasoning_traces table (PostgreSQL would require the partition key in the
    # FK); linkage integrity is enforced by tests (cf. raw_artifact_id, M1-18).
    op.create_table(
        "reasoning_trace_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("tool_name", sa.String(length=255), nullable=True),
        sa.Column("evidence", _JSON, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("pk_reasoning_trace_steps")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        op.f("ix_reasoning_trace_steps_trace_id"), "reasoning_trace_steps", ["trace_id"]
    )


def _create_partitions() -> None:
    if not _is_postgresql():
        return
    for parent in _PARTITIONED_TABLES:
        for suffix, lower, upper in _PARTITION_WINDOWS:
            op.execute(
                f"CREATE TABLE {parent}_{suffix} PARTITION OF {parent} "
                f"FOR VALUES FROM ('{lower}') TO ('{upper}')"
            )
        op.execute(f"CREATE TABLE {parent}_default PARTITION OF {parent} DEFAULT")


def _link_audit_log_to_traces() -> None:
    # Nullable, plain indexed UUID linking an audited action to the reasoning
    # trace that produced it (brief §6). No FK: audit_log AND reasoning_traces
    # are both partitioned. ADD COLUMN on the partitioned parent propagates to
    # every partition; CREATE INDEX on the parent creates a partitioned index.
    op.add_column("audit_log", sa.Column("reasoning_trace_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_audit_log_reasoning_trace_id"), "audit_log", ["reasoning_trace_id"])


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------


def downgrade() -> None:
    op.drop_index(op.f("ix_audit_log_reasoning_trace_id"), table_name="audit_log")
    op.drop_column("audit_log", "reasoning_trace_id")

    if _is_postgresql():
        # Drop partitions in reverse creation order before the parents (DROP
        # TABLE on the parent would cascade, but keep the reverse literal).
        for parent in reversed(_PARTITIONED_TABLES):
            op.execute(f"DROP TABLE {parent}_default")
            for suffix, _lower, _upper in reversed(_PARTITION_WINDOWS):
                op.execute(f"DROP TABLE {parent}_{suffix}")

    op.drop_table("reasoning_trace_steps")
    op.drop_table("reasoning_traces")
    op.drop_table("agent_sessions")
