"""M4 schema: config_snapshots, compliance_policies, documents, embeddings.

Hand-written (not autogenerated) so the PostgreSQL-only pgvector DDL — the
``vector`` extension, the ``VECTOR(EMBEDDING_DIM)`` column, and the HNSW/cosine
index — can be expressed. On the postgresql dialect ``embeddings.embedding`` is
a ``vector`` column with an HNSW index using ``vector_cosine_ops`` (ADR-0004 §3);
on other dialects (the SQLite unit-test backend) the column is created as TEXT
and the index DDL is skipped, mirroring how ``app.models.config_mgmt`` declares
the portable ``VECTOR_VARIANT``.

None of these tables are partitioned, so every FK is a real DB-level FK:
``config_snapshots.device_id`` → ``devices``, ``documents.generated_by_session_id``
→ ``agent_sessions``, ``embeddings.document_id`` → ``documents``.

Tables (ADR-0004 §2, ADR-0017/0018/0019):
- ``config_snapshots`` — verbatim, content-addressed configs; ``(device_id,
  content_hash)`` unique dedups unchanged re-captures; ``baseline`` marks the
  last-approved config per device.
- ``compliance_policies`` — one declarative YAML policy version per row;
  ``(policy_id, version)`` unique; ``scope`` + ``rules`` as JSONB.
- ``documents`` — generated inventory/diagram/runbook artifacts.
- ``embeddings`` — pgvector chunk embeddings; ``(document_id, chunk_index)``
  unique so re-embedding replaces chunks without orphan vectors.

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-14
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Portable JSON column: plain JSON everywhere, JSONB on PostgreSQL. Mirrors
#: app.models.mixins.JSON_VARIANT (migrations never import models — D4).
_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

#: Embedding vector dimension of the default local profile (nomic-embed-text →
#: 768, ADR-0009 §6). Kept in sync with app.models.config_mgmt.EMBEDDING_DIM;
#: migrations do not import models (D4). A model change is a re-embed migration.
_EMBEDDING_DIM = 768


def _is_postgresql() -> bool:
    """Dialect guard safe in both online and offline (``--sql``) mode."""
    return op.get_context().dialect.name == "postgresql"


def _embedding_column() -> sa.Column[object]:
    """``vector(N)`` on PostgreSQL, ``TEXT`` elsewhere (parity with the ORM)."""
    column_type: sa.types.TypeEngine[Any]
    if _is_postgresql():
        from pgvector.sqlalchemy import Vector

        column_type = Vector(_EMBEDDING_DIM)
    else:
        column_type = sa.Text()
    return sa.Column("embedding", column_type, nullable=False)


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------


def upgrade() -> None:
    _enable_pgvector()
    _create_config_snapshots()
    _create_compliance_policies()
    _create_documents()
    _create_embeddings()


def _enable_pgvector() -> None:
    # The ``vector`` column type and HNSW index require the pgvector extension.
    if _is_postgresql():
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def _create_config_snapshots() -> None:
    op.create_table(
        "config_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("capture_run_id", sa.Uuid(), nullable=True),
        sa.Column("baseline", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_config_snapshots")),
        sa.UniqueConstraint("device_id", "content_hash", name="uq_config_snapshots_device_hash"),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_config_snapshots_device_id")
        ),
    )
    op.create_index(op.f("ix_config_snapshots_device_id"), "config_snapshots", ["device_id"])
    op.create_index(op.f("ix_config_snapshots_content_hash"), "config_snapshots", ["content_hash"])
    op.create_index(
        op.f("ix_config_snapshots_capture_run_id"), "config_snapshots", ["capture_run_id"]
    )


def _create_compliance_policies() -> None:
    op.create_table(
        "compliance_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scope", _JSON, nullable=False),
        sa.Column("rules", _JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compliance_policies")),
        sa.UniqueConstraint("policy_id", "version", name="uq_compliance_policies_policy_version"),
    )
    op.create_index(op.f("ix_compliance_policies_policy_id"), "compliance_policies", ["policy_id"])


def _create_documents() -> None:
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_refs", _JSON, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_by_session_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.ForeignKeyConstraint(
            ["generated_by_session_id"],
            ["agent_sessions.id"],
            name=op.f("fk_documents_generated_by_session_id"),
        ),
    )
    op.create_index(op.f("ix_documents_kind"), "documents", ["kind"])
    op.create_index(
        op.f("ix_documents_generated_by_session_id"),
        "documents",
        ["generated_by_session_id"],
    )


def _create_embeddings() -> None:
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        _embedding_column(),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_embeddings_document_chunk"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_embeddings_document_id")
        ),
    )
    op.create_index(op.f("ix_embeddings_document_id"), "embeddings", ["document_id"])

    # HNSW / cosine index on the pgvector column (ADR-0004 §3) — PostgreSQL only.
    if _is_postgresql():
        op.execute(
            "CREATE INDEX ix_embeddings_embedding_hnsw ON embeddings "
            "USING hnsw (embedding vector_cosine_ops)"
        )


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------


def downgrade() -> None:
    if _is_postgresql():
        op.execute("DROP INDEX IF EXISTS ix_embeddings_embedding_hnsw")
    op.drop_index(op.f("ix_embeddings_document_id"), table_name="embeddings")
    op.drop_table("embeddings")

    op.drop_index(op.f("ix_documents_generated_by_session_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_kind"), table_name="documents")
    op.drop_table("documents")

    op.drop_index(op.f("ix_compliance_policies_policy_id"), table_name="compliance_policies")
    op.drop_table("compliance_policies")

    op.drop_index(op.f("ix_config_snapshots_capture_run_id"), table_name="config_snapshots")
    op.drop_index(op.f("ix_config_snapshots_content_hash"), table_name="config_snapshots")
    op.drop_index(op.f("ix_config_snapshots_device_id"), table_name="config_snapshots")
    op.drop_table("config_snapshots")
    # The pgvector extension is left installed on downgrade (other objects may
    # depend on it; DROP EXTENSION is an operator decision, not a migration's).
