"""M5 task #2: change_requests + approvals spine, pcap_metadata.

Hand-written (not autogenerated) so the PostgreSQL-only four-eyes *constraint
trigger* DDL can be expressed. The cross-table four-eyes rule (an ``approvals``
row with ``decision = 'approve'`` may not have ``actor_id =
change_requests.requester_id`` for that CR) cannot be a single-row ``CHECK``
because a CHECK cannot reference another table — so it is a PL/pgSQL constraint
trigger (ADR-0020 §2). It is **conditional on ``four_eyes_required``**: it raises
only when the CR's ``four_eyes_required = true`` AND the decision is an approve
AND ``actor_id = requester_id``. An unconditional trigger would reject the very
self-approval the documented ``four_eyes_required = false`` mode is meant to
allow, making that mode unbuildable. On other dialects (the SQLite unit-test
backend) the trigger is a no-op — the four-eyes predicate is unit-tested through
the service guard; this DB backstop is exercised by the ``integration``-marked
migration test in both the enabled (self-approval rejected) and disabled
(self-approval allowed + audited) paths.

Tables (ADR-0020 §2, ADR-0023 §3):
- ``change_requests`` — the single spine for every state-changing action;
  ``state`` lifecycle enum, ``kind`` (config / ddi_record), ``before_state`` /
  ``after_state`` JSONB, real FK ``requester_id`` → ``users``,
  ``four_eyes_required`` NOT NULL DEFAULT true, plain indexed ``reasoning_trace_id``
  (no FK — ``reasoning_traces`` is partitioned, cf. ``audit_log``).
- ``approvals`` — append-only approve/reject decision history; real FKs
  ``change_request_id`` → ``change_requests`` and ``actor_id`` → ``users``.
- ``pcap_metadata`` — capture metadata + retention/tombstone/audit record; real
  FK ``requester_id`` → ``users``, nullable FK ``device_id`` → ``devices``
  (worker-side tcpdump has no device); ``capture_id`` unique; ``tombstoned_*``
  set by the retention job (the row is never hard-deleted).

None of these tables are partitioned, so every users/devices/CR FK is a real
DB-level FK.

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-18
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Portable JSON column: plain JSON everywhere, JSONB on PostgreSQL. Mirrors
#: app.models.mixins.JSON_VARIANT (migrations never import models — D4).
_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

# ``state`` / ``kind`` / ``decision`` are persisted as VARCHAR (the ORM uses
# native_enum=False), so the columns are plain String here — migrations never
# import the StrEnums (D4).

#: PL/pgSQL guard for the cross-table, four_eyes_required-conditional four-eyes
#: rule. Raises only when the CR requires four-eyes AND this is an approve by the
#: requester themself. A reject self-decision and any decision on a CR with
#: four_eyes_required = false pass through (ADR-0020 §2).
_FOUR_EYES_FUNCTION = """
CREATE FUNCTION enforce_four_eyes() RETURNS trigger AS $$
DECLARE
    cr_requester uuid;
    cr_four_eyes boolean;
BEGIN
    SELECT requester_id, four_eyes_required
      INTO cr_requester, cr_four_eyes
      FROM change_requests
     WHERE id = NEW.change_request_id;

    IF cr_four_eyes AND NEW.decision = 'approve' AND NEW.actor_id = cr_requester THEN
        RAISE EXCEPTION
            'four-eyes violation: approver (%) must differ from requester (%) '
            'for change_request %', NEW.actor_id, cr_requester, NEW.change_request_id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_FOUR_EYES_TRIGGER = """
CREATE CONSTRAINT TRIGGER trg_approvals_four_eyes
    AFTER INSERT OR UPDATE ON approvals
    DEFERRABLE INITIALLY IMMEDIATE
    FOR EACH ROW EXECUTE FUNCTION enforce_four_eyes();
"""


def _is_postgresql() -> bool:
    """Dialect guard safe in both online and offline (``--sql``) mode."""
    return op.get_context().dialect.name == "postgresql"


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------


def upgrade() -> None:
    _create_change_requests()
    _create_approvals()
    _create_four_eyes_trigger()
    _create_pcap_metadata()


def _create_change_requests() -> None:
    op.create_table(
        "change_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("before_state", _JSON, nullable=True),
        sa.Column("after_state", _JSON, nullable=True),
        sa.Column("four_eyes_required", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("reasoning_trace_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_requests")),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name=op.f("fk_change_requests_requester_id")
        ),
    )
    op.create_index(op.f("ix_change_requests_state"), "change_requests", ["state"])
    op.create_index(op.f("ix_change_requests_requester_id"), "change_requests", ["requester_id"])
    # Plain indexed UUID linking a CR to the reasoning trace that authored it.
    # No FK: reasoning_traces is partitioned (cf. audit_log.reasoning_trace_id).
    op.create_index(
        op.f("ix_change_requests_reasoning_trace_id"),
        "change_requests",
        ["reasoning_trace_id"],
    )


def _create_approvals() -> None:
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("change_request_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.ForeignKeyConstraint(
            ["change_request_id"],
            ["change_requests.id"],
            name=op.f("fk_approvals_change_request_id"),
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_approvals_actor_id")),
    )
    op.create_index(op.f("ix_approvals_change_request_id"), "approvals", ["change_request_id"])
    op.create_index(op.f("ix_approvals_actor_id"), "approvals", ["actor_id"])


def _create_four_eyes_trigger() -> None:
    # DB-level four-eyes backstop (ADR-0020 §2), PostgreSQL only. Conditional on
    # change_requests.four_eyes_required so the documented disabled-self-approval
    # mode stays reachable; SQLite skips it (the service guard is the unit path).
    if not _is_postgresql():
        return
    op.execute(_FOUR_EYES_FUNCTION)
    op.execute(_FOUR_EYES_TRIGGER)


def _create_pcap_metadata() -> None:
    op.create_table(
        "pcap_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capture_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("interface", sa.String(length=255), nullable=False),
        sa.Column("capture_filter", sa.Text(), nullable=True),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("byte_count", sa.BigInteger(), nullable=True),
        sa.Column("packet_count", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tombstoned_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pcap_metadata")),
        sa.UniqueConstraint("capture_id", name="uq_pcap_metadata_capture_id"),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_pcap_metadata_device_id")
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name=op.f("fk_pcap_metadata_requester_id")
        ),
    )
    op.create_index(op.f("ix_pcap_metadata_device_id"), "pcap_metadata", ["device_id"])
    op.create_index(op.f("ix_pcap_metadata_requester_id"), "pcap_metadata", ["requester_id"])
    op.create_index(op.f("ix_pcap_metadata_tombstoned_at"), "pcap_metadata", ["tombstoned_at"])


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------


def downgrade() -> None:
    op.drop_index(op.f("ix_pcap_metadata_tombstoned_at"), table_name="pcap_metadata")
    op.drop_index(op.f("ix_pcap_metadata_requester_id"), table_name="pcap_metadata")
    op.drop_index(op.f("ix_pcap_metadata_device_id"), table_name="pcap_metadata")
    op.drop_table("pcap_metadata")

    if _is_postgresql():
        op.execute("DROP TRIGGER IF EXISTS trg_approvals_four_eyes ON approvals")
        op.execute("DROP FUNCTION IF EXISTS enforce_four_eyes()")

    op.drop_index(op.f("ix_approvals_actor_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_change_request_id"), table_name="approvals")
    op.drop_table("approvals")

    op.drop_index(op.f("ix_change_requests_reasoning_trace_id"), table_name="change_requests")
    op.drop_index(op.f("ix_change_requests_requester_id"), table_name="change_requests")
    op.drop_index(op.f("ix_change_requests_state"), table_name="change_requests")
    op.drop_table("change_requests")
