/**
 * Incident Reports: list and download agent-generated incident reports.
 *
 * Incident reports are ``Document`` rows with ``kind="incident_report"``
 * (generated by the M5 T12 Documentation Agent extension). This page:
 *  - lists all incident-report documents via ``GET /docs?kind=incident_report``
 *  - renders each report inline (Markdown ``pre``-formatted, mirroring
 *    DocumentsPage ContentPanel)
 *  - downloads via ``GET /docs/{id}/download`` → Blob download (.md)
 *
 * Read-only view. Mirrors DocumentsPage conventions (ADR-0019).
 */

import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { downloadDocument, listDocuments, type DocumentRead } from "../api/docs";
import { PageHeader } from "../components/PageHeader";

// ── Report row ────────────────────────────────────────────────────────────────

function ReportRow({
  doc,
  onView,
  onDownload,
}: {
  doc: DocumentRead;
  onView: (doc: DocumentRead) => void;
  onDownload: (doc: DocumentRead) => void;
}) {
  return (
    <tr
      data-testid={`incident-row-${doc.id}`}
      className="border-b border-carbon-800 last:border-0"
    >
      <td className="px-4 py-3 text-zinc-200">
        <span className="text-sm font-medium">{doc.title}</span>
      </td>
      <td className="px-4 py-3 font-mono text-[11px] text-zinc-500">
        {new Date(doc.generated_at).toLocaleString()}
      </td>
      <td className="px-4 py-3">
        <div className="flex items-center gap-2">
          <button
            type="button"
            data-testid={`incident-view-${doc.id}`}
            onClick={() => onView(doc)}
            className="rounded border border-carbon-600 px-2 py-1 font-mono text-[11px] uppercase tracking-wider text-zinc-400 transition-colors hover:border-carbon-500 hover:text-zinc-200"
          >
            View
          </button>
          <button
            type="button"
            data-testid={`incident-download-${doc.id}`}
            onClick={() => onDownload(doc)}
            className="rounded border border-carbon-600 px-2 py-1 font-mono text-[11px] uppercase tracking-wider text-zinc-400 transition-colors hover:border-carbon-500 hover:text-zinc-200"
          >
            Download
          </button>
        </div>
      </td>
    </tr>
  );
}

// ── Inline report panel ───────────────────────────────────────────────────────

function ReportPanel({
  doc,
  onClose,
}: {
  doc: DocumentRead;
  onClose: () => void;
}) {
  return (
    <div
      data-testid="incident-report-panel"
      className="flex flex-col gap-4 rounded-md border border-carbon-700 bg-carbon-900 p-4"
    >
      <div className="flex items-center justify-between">
        <h3 className="font-mono text-xs font-semibold uppercase tracking-widest text-zinc-300">
          {doc.title}
        </h3>
        <button
          type="button"
          data-testid="incident-panel-close"
          onClick={onClose}
          className="rounded border border-carbon-600 px-3 py-1 font-mono text-[11px] uppercase tracking-wider text-zinc-400 transition-colors hover:border-carbon-500 hover:text-zinc-200"
        >
          Close
        </button>
      </div>
      <pre
        data-testid="incident-report-content"
        aria-label="Incident report content"
        className="overflow-x-auto rounded bg-carbon-950 p-4 font-mono text-[11px] leading-relaxed text-zinc-300"
      >
        {doc.content}
      </pre>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export function IncidentReportsPage() {
  const [viewedDoc, setViewedDoc] = useState<DocumentRead | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  const { data, isPending, error } = useQuery({
    queryKey: ["incident-reports"],
    // "incident_report" is the M5-T12 document kind stored by the Documentation
    // Agent (ADR-0019). DocumentKind includes "incident_report" so no cast is needed.
    queryFn: () =>
      listDocuments({ kind: "incident_report", limit: 50 }),
  });

  async function handleDownload(doc: DocumentRead): Promise<void> {
    try {
      setDownloadError(null);
      const payload = await downloadDocument(doc.id);
      const blob = new Blob([payload.content], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${payload.title.replace(/\s+/g, "-").toLowerCase()}.md`;
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 0);
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : "Download failed");
    }
  }

  const items = data?.items ?? [];

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Incident Reports"
        description="Agent-generated incident reports from troubleshooting sessions. Each report contains timeline, evidence references, and redacted network data (M5 T12)."
      />

      {/* Loading */}
      {isPending && (
        <p role="status" className="text-xs text-zinc-500">
          Loading incident reports…
        </p>
      )}

      {/* Load error */}
      {error && (
        <div
          role="alert"
          className="panel border-status-error/40 px-4 py-3 text-xs text-status-error"
        >
          Failed to load incident reports: {error.message}
        </div>
      )}

      {/* Download error */}
      {downloadError !== null && (
        <div
          role="alert"
          data-testid="incident-download-error"
          className="panel border-status-error/40 px-4 py-3 text-xs text-status-error"
        >
          Download failed: {downloadError}
        </div>
      )}

      {/* Empty state */}
      {!isPending && !error && items.length === 0 && (
        <div
          data-testid="incident-empty-state"
          className="flex flex-col items-center justify-center gap-2 rounded-md border border-dashed border-carbon-600 bg-carbon-900/50 px-6 py-16 text-center"
        >
          <p className="text-sm font-medium text-zinc-200">No incident reports yet</p>
          <p className="max-w-md text-xs leading-relaxed text-zinc-500">
            Incident reports are generated by the Documentation Agent from
            troubleshooting sessions. Run a session and request an incident report
            via the Chat interface to populate this view.
          </p>
        </div>
      )}

      {/* Report table */}
      {!isPending && !error && items.length > 0 && (
        <div className="flex flex-col gap-4">
          <div className="panel overflow-x-auto">
            <table className="w-full text-xs" data-testid="incident-reports-table">
              <thead>
                <tr className="border-b border-carbon-700 text-left text-zinc-500">
                  <th className="px-4 py-2 font-medium">Title</th>
                  <th className="px-4 py-2 font-medium">Generated</th>
                  <th className="px-4 py-2 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody>
                {items.map((doc: DocumentRead) => (
                  <ReportRow
                    key={doc.id}
                    doc={doc}
                    onView={setViewedDoc}
                    onDownload={handleDownload}
                  />
                ))}
              </tbody>
            </table>
            <p
              data-testid="incident-total-count"
              className="px-4 py-2 text-[11px] text-zinc-600"
            >
              {data?.total ?? 0}
            </p>
          </div>

          {/* Inline report panel */}
          {viewedDoc !== null && (
            <div className="mt-2">
              <ReportPanel doc={viewedDoc} onClose={() => setViewedDoc(null)} />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
